- src/Chat/Plugin/Urban.php
> managing empty results

- src/Chat/Plugin/Docs.php
#4 
This should work in 99% of cases. I recall there being some oddities that would need to be special-cased, but I forget what they are. This should do for now, they can be fixed as and when they are found.
> Basic implementation for #4

- src/Chat/Plugin/Docs.php
See http://chat.stackoverflow.com/transcript/message/29555324#29555324
> Fix Docs Plugin for foreach and the like

- src/Chat/Plugin/Rebecca.php
Adds a Rebecca command. Will post the video link to Friday on Fridays.
Will give appropriate messages on every other day than Friday.
> Add Rebecca command

- src/Chat/Plugin/Rebecca.php
Because you know you can't wait!
> Add Rebeccaday countdown (for extra excitement)!

- src/Chat/Plugin/Rebecca.php
You did not see this! :see_no_evil:
> Fixed a glitch in the Matrix

- src/Chat/Client/ChatClient.php
> Fixed typo

- src/Chat/Plugin/Tweet.php
http://chat.stackoverflow.com/transcript/message/30685893#30685893
> Don't reply, just post the tweet URL

- src/Chat/Plugin/Github.php
Status usage:
!!github status
or shorthand:
!!github
About a user/org:
!!github Room-11
About a repo:
!!github Room-11/Jeeves
> Add Github Plugin

- src/Plugins/Should.php
http://chat.stackoverflow.com/transcript/message/31423190#31423190
> Fix my - your bug in `!!should`

- src/Plugins/EvalCode.php
The extra wrapping of output in another array was a bug.
> Bugfix; output has too many levels

- src/Plugins/Goochle.php
It's not tested so I assume it's fine.
> Add Goochle Trenslete plugin.

- config/config.sample.yml
- src/Plugins/Changelog.php
Gets the last commit for a given repo
> Add changelog plugin

- src/Plugins/RFC.php
http://chat.stackoverflow.com/transcript/message/32733330#32733330
> Unpin previous message if there are no RFCs in voting

- src/Chat/Client/Chars.php
- src/External/BitlyClient.php
- src/Plugins/Canon.php
- src/helpers.php
No more const array \o/ and a new SE URL Normalizer (helper) thanks to @DaveRandom
> KeyValueStore for Canon plugin

- config/config.sample.yml
- src/Plugins/AntiW3Schools.php
* Rearranged the sample config file and added the plugin to the list.
* Removed an extra "MySQL" in the sql response.
Tried adding a LogicException on a bad regex response, but was a bit concerned that it would fire on every message.
> Small AntiW3Schools plugin tweaks.

- config/config.sample.yml
A dumb commit by a dumb person.
> Correction to default plugin list

- src/Plugins/Scrabble.php
allows Jeeves to calculate the Scrabble score of the passed input string. Currently only supports the original english scoring.
> add Scrabble plugin

- config/config.sample.yml
- src/Plugins/Lmgtfy.php
https://github.com/Room-11/Jeeves/issues/62
> lmgtfy plugin

- src/Plugins/Github.php
http://chat.stackoverflow.com/transcript/message/33631865#33631865 /cc @J7mbo
> auto Github status checker

- src/Plugins/Rebecca.php
Now with 100% less merge screwups :)
> Rebecca - Saturday video link v2

- src/Plugins/Imdb.php
Related to #54, uses the OMDB API to pull back multiple search results. Will edit in descriptions and ratings for the films after further processing.
Feedback is absolutely necessary, the initial PR is a skeleton version and does not handle validation or sanitation between Jeeves and OMDB.
> Changing !!imdb to use the OMDB Api

- src/Plugins/Github.php
> GH Bug fix

- src/Plugins/Terminator.php
> much smart-arse

- cli/run.php
- src/BuiltIn/Commands/Remove.php
- src/Chat/Client/Actions/ActionFactory.php
- src/Chat/Client/Actions/MoveMessageAction.php
- src/Chat/Client/ChatClient.php
- src/Chat/Endpoint.php
- src/Chat/EndpointURLResolver.php
> Added built in remove command

- src/Plugins/Issue.php
> Added limit to explode()

- .travis.yml
- README.md
- composer.json
[Blame Jay](https://github.com/Room-11/Jeeves/blob/3599efaaf8edb625ad5558b7b81caef5db1dfa89/src/Chat/Client/ChatClient.php#L522).
> Updated the minimum requirement of PHP from 7.0 to 7.1

- src/Plugins/Imdb.php
Mainly in response to http://chat.stackoverflow.com/transcript/message/35700883#35700883
where the plugin wasn't handling when the API was down.
> Imdb Tweaks

- README.md
- bin/jeeves
- config/jeeves.sample.service
- src/bootstrap.php
- src/launcher.php
- src/setup-di.php
This is what I propose.
`bootstrap.php` can be shared with the test startup routine (?)
> Refactor startup layout

- README.md
Courtesy of http://chat.stackoverflow.com/transcript/message/36051214#36051214
> Add proper attribution

- src/Plugins/RFC.php
Attempt to fix issue where calls to !!voting are hanging forever.
> Add Connection: close to RFC HttpRequest calls.

- src/Plugins/CanIUse.php
- tests/src/Plugin/CanIUseTest.php
> Fix for CanIUse encoding the URI correctly (as per #198)

- src/Plugins/Tweet.php
- src/Utf8Chars.php
- Convert [tag] into #tag
- Better link handling in general
- Check if links are uploadable media and upload them if they are
> Tweet improvements

- src/Plugins/Github.php
`!!github status` and passive polling now report when github's status page is unreachable.
Passive polling must fail for 3 consecutive attempts before it reports.
All failed attempts generate log warnings.
> Github status improvements for #225

- src/Chat/WebSocketEventDispatcher.php
Useful for testing on the same account as the bot.
> Allows Jeeves to reply to it's own commands when dev mode is enabled.

- src/Plugins/PHPBugs.php
I vaguely remember someone wanting this.
Also was getting errors with the existing table selection code that apparently live jeeves isn't? I hope the html we're fed isn't so dissimilar that the query I used instead breaks.
> Use bug type for tag

- src/Plugins/Terminator.php
Modified the position of 'favorite color question' and added 'how do you take your coffee' question.
> Modified $patterns

- src/Plugins/Wotd.php
Have added  https://www.merriam-webster.com/word-of-the-day as an alternative WOTD, in case the primary doesn't work.
> Alternate for WOTD added
